---
home:
  url: https://genenetwork.org/
repo: gn-gemtext-threads
git-home: https://github.com/genenetwork/gn-gemtext-threads
git-edit-prefix: https://github.com/genenetwork/gn-gemtext-threads/edit/main

